import esbuild from "esbuild";
import cssModulesPlugin from "esbuild-css-modules-plugin";

import process from "process";
import builtins from "builtin-modules";
import path from "path";
import fs from "fs/promises";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

// 方便直接调试, 具体打包输出路径可自行更改
const outdir = path.resolve(process.cwd(), "../knowledge/PARA/.obsidian/plugins/obsidian-ai-chat");
const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir,
	jsx: "automatic",
	jsxImportSource: "react",
	// 添加 CSS 加载器
	loader: {
		".css": "css",  // 将 CSS 作为文本导入
		".tsx": "tsx",
		".ts": "ts"
	},
	plugins: [
		cssModulesPlugin({
			inject: false,            // 不注入 <style>，而是生成独立 CSS 文件
			cssOutputFile: "styles1.css" // 输出到 outdir/styles.css（Obsidian 会读取这个文件）
		})
	]
});

async function copyStatic() {
  await fs.mkdir(outdir, { recursive: true });
  await fs.copyFile("manifest.json", path.join(outdir, "manifest.json"));
  // await fs.copyFile("styles.css", path.join(outdir, "styles.css"));
}

if (prod) {
	await context.rebuild();
	await copyStatic();
	process.exit(0);
} else {
	await context.watch();
	await copyStatic();
}
